architect:
- carlosmiranda
- yegor256
- davvd
install:
- sudo gem install pdd
assets:
  secring.gpg: zerocracy/home#assets/secring.gpg
  settings.xml: zerocracy/home#assets/xembly/settings.xml
  pubring.gpg: zerocracy/home#assets/pubring.gpg
  s3cfg: zerocracy/home#assets/s3cfg
merge:
  commanders: []
  script: |-
    mvn clean install -Pxembly -Pqulice --errors --settings ../settings.xml
    mvn clean site -Psite --errors --settings ../settings.xml -Dinvoker.skip
    mvn clean
    pdd --source=$(pwd) --verbose --file=/dev/null
deploy:
  script: |-
    mvn clean deploy -Pqulice --errors --settings ../settings.xml
    mvn clean
    pdd --source=$(pwd) --verbose --file=xembly.xml
    s3cmd --no-progress put xembly.xml --config=../s3cfg s3://pdd.teamed.io/xembly.xml
env:
  MAVEN_OPTS: -XX:MaxPermSize=256m -Xmx1g
release:
  script: |-
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Pxembly -Psonatype --errors --settings ../settings.xml
    mvn clean site-deploy -Pxembly -Psite --errors --settings ../settings.xml -Dinvoker.skip
  commanders:
  - yegor256
